Fix "Live Updates" workflow errors when branch already exists

diff --git a/.github/workflows/live-updates.yml b/.github/workflows/live-updates.yml
--- a/.github/workflows/live-updates.yml
+++ b/.github/workflows/live-updates.yml
@@ -57,6 +57,7 @@ jobs:
             if grep -q 'export.*liveUpdate' "$package/project.bri"; then
               echo "::group::$package"
 
+              git fetch --depth=1 origin "$branch_name" || echo "No existing branch for package $package"
               git checkout "origin/${branch_name}" || git checkout "${git_head}"
               git clean -ffdx
               if ! brioche live-update -p "$package" --locked; then
@@ -98,8 +99,12 @@ jobs:
             pr_title="[${package_name}] (Live update)"
             pr_body=$(echo -e "Automatic update for ${package_name}\n\nGenerated by workflow [${run_label}](${run_url})")
 
-            git push origin "$branch"
-            gh pr create --head "$branch" --title "$pr_title" --body "$pr_body" --label "live update" || gh pr comment "$branch" --body "$pr_body"
+            if git push origin "$branch"; then
+              gh pr create --head "$branch" --title "$pr_title" --body "$pr_body" --label "live update" || gh pr comment "$branch" --body "$pr_body"
+            else
+              echo "::error::Failed to push $branch"
+              echo "Failed to push branch $branch" >> failed-packages.txt
+            fi
           done
         env:
           run_label: "${{ github.workflow }} #${{ github.run_number}}"
