Minor GitHub Actions workflow fixes and tweaks (#502)
* Fix "Live Updates" workflow errors when branch already exists

* Update GH Actions workflows to show # of packages in group labels

* Update build workflow to print output from failed processes

diff --git a/.github/workflows/live-updates.yml b/.github/workflows/live-updates.yml
--- a/.github/workflows/live-updates.yml
+++ b/.github/workflows/live-updates.yml
@@ -46,17 +46,20 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           git_head="$(git rev-parse HEAD)"
-
-          packages_glob="packages/*"
-          packages=( $packages_glob )
+          packages=(packages/*)
           mapfile -t packages < <(printf '%s\n' "${packages[@]}" | sort -R) # Shuffle the packages
           failed_packages=()
 
+          n=1
           for package in "${packages[@]}"; do
             branch_name="live-update/$(basename "$package")"
-            if grep -q 'export.*liveUpdate' "$package/project.bri"; then
-              echo "::group::$package"
+            label="$package ($n / ${#packages[@]})"
+            ((n++))
 
+            if grep -q 'export.*liveUpdate' "$package/project.bri"; then
+              echo "::group::$label"
+
+              git fetch --depth=1 origin "$branch_name" || echo "No existing branch for package $package"
               git checkout "origin/${branch_name}" || git checkout "${git_head}"
               git clean -ffdx
               if ! brioche live-update -p "$package" --locked; then
@@ -77,7 +80,7 @@ jobs:
 
               echo "::endgroup::"
             else
-              echo "$package: no live-update found"
+              echo "$label: no live-update found"
             fi
           done
 
@@ -98,8 +101,12 @@ jobs:
             pr_title="[${package_name}] (Live update)"
             pr_body=$(echo -e "Automatic update for ${package_name}\n\nGenerated by workflow [${run_label}](${run_url})")
 
-            git push origin "$branch"
-            gh pr create --head "$branch" --title "$pr_title" --body "$pr_body" --label "live update" || gh pr comment "$branch" --body "$pr_body"
+            if git push origin "$branch"; then
+              gh pr create --head "$branch" --title "$pr_title" --body "$pr_body" --label "live update" || gh pr comment "$branch" --body "$pr_body"
+            else
+              echo "::error::Failed to push $branch"
+              echo "Failed to push branch $branch" >> failed-packages.txt
+            fi
           done
         env:
           run_label: "${{ github.workflow }} #${{ github.run_number}}"
