Update "Live Updates" GH Actions workflow (#412)
* Fix failed branches in "Live update" workflow not printing anything

* Add error annotation when package update fails

* Update "Live Updates" workflow to return an error if any updates fail

* Run "Live Updates" workflow on a schedule

diff --git a/.github/workflows/live-updates.yml b/.github/workflows/live-updates.yml
--- a/.github/workflows/live-updates.yml
+++ b/.github/workflows/live-updates.yml
@@ -2,6 +2,8 @@ name: Live updates
 
 on:
   workflow_dispatch:
+  schedule:
+    - cron: '17 12 * * FRI' # Every Friday at 12:17pm UTC
 
 jobs:
   live-update-packages:
@@ -41,6 +43,7 @@ jobs:
       - name: Update packages
         run: |
           git_head="$(git rev-parse HEAD)"
+          failed_packages=()
 
           for package in packages/*; do
             branch_name="live-update/$(basename "$package")"
@@ -50,8 +53,10 @@ jobs:
               git checkout "origin/${branch_name}" || git checkout "${git_head}"
               git clean -ffdx
               if ! brioche live-update -p "$package" --locked; then
-                continue
                 echo "🔴 Failed to update $package"
+                echo "::error file=$package/project.bri::Failed to update $package"
+                failed_packages+=( "$package" )
+                continue
               fi
 
               if [ -n "$(git status --porcelain)" ]; then
@@ -68,6 +73,9 @@ jobs:
               echo "$package: no live-update found"
             fi
           done
+
+          git checkout "$git_head"
+          printf "%s\n" "${failed_packages[@]}" > failed-packages.txt
 
       - name: Configure git credentials
         run: git remote set-url origin "$auth_url"
@@ -90,3 +98,11 @@ jobs:
           run_label: "${{ github.workflow }} #${{ github.run_number}}"
           run_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
           GH_TOKEN: ${{ steps.app-token.outputs.token }}
+
+      - name: Check for failed packages
+        run: |
+          if [ -n "$(cat failed-packages.txt)" ]; then
+            echo "The following package live updates failed:"
+            cat failed-packages.txt
+            exit 1
+          fi
